services:
  agarden:
    container_name: agarden
    image: ghcr.io/realtpowell/agarden:latest
    ports: []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agarden.rule=Host(`trpowell.net`)"
      - "traefik.http.routers.agarden.entrypoints=websecure"
      - "traefik.http.routers.agarden.tls.certresolver=myresolver"

  reverse-proxy:
    image: traefik:v3.5
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Let's Encrypt configuration
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=trpowell@protonmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

volumes:
  letsencrypt:
