# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global", assets]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Tom Powell / %s"
og_image: /assets/img/og_emma.png
author: Tom Powell
favicon: /assets/img/favicon.jpg
description: Learning how to make a blog!
port: 8083

# OG image
origin: https://simple-blog.nuejs.org
og: /assets/img/og.jpg


navigation:
  header:
    - agarden: /
    - by Tom Powell: /about/

  footer:
    - image: /assets/img/github.svg
      url: //github.com/nuejs/nue/
      alt: Github Projects
      size: 22 x 22

    - image: /assets/img/linkedin.svg
      url: //linkedin.com/in/tipiirai
      alt: LinkedIn profile
      size: 22 x 22
